apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: anantlad28/aj_store:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URL
              value: mongodb+srv://anantlad018:anantlad018@cluster0.rpdlhx1.mongodb.net/aj_store?retryWrites=true&w=majority

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000